spring:
  datasource:
    url: jdbc:sqlite:financeiro.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect

api:
  url: "https://api.hgbrasil.com/finance?format=json-cors&"
  key: ${API_KEY}
  cmc-url: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
  cmc-key: ${API_CMC_KEY}
  # Fallback
  coingecko-url: "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"

management:
  endpoint:
    health:
      show-details: always