spring:
  datasource:
    url: jdbc:sqlite:financeiro.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect

api:
  url: "https://api.hgbrasil.com/finance?format=json-cors&"
  key: ${API_KEY}
  coincap-url: "https://api.coincap.io/v2/assets?limit=10"
  binance-url: "https://api.binance.com/api/v3/ticker/price"

management:
  endpoint:
    health:
      show-details: always