spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 7
      minimum-idle: 1
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

api:
  url: "https://api.hgbrasil.com/finance?format=json-cors&"
  key: ${API_KEY}
  cmc-url: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
  cmc-key: ${API_CMC_KEY}
  # Fallback
  coingecko-url: "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  gov-url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.{codigo}/dados/ultimos/1?formato=json"
  brapi-url: "https://brapi.dev/api/quote/{tickers}?token={token}"
  brapi-token: ${API_BRAPI_KEY}
