spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


brevo:
  api:
    key: ${BREVO_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.gestao.financeira: WARN

app:
  frontend-url: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

  email:
    from:
      name: FinanceX
      address: ${BREVO_EMAIL_FROM}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000