spring:
  datasource:
    url: jdbc:sqlite:financeiro.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect

exchange:
  api:
    url: "https://v6.exchangerate-api.com/v6/"
    key: "9cbf2d799fc41c696e69f561"

app:
  frontend:
    url: http://localhost:3000